# Generated by Django 5.2.1 on 2025-05-19 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('cortico', 'Cortiço'), ('outro', 'Outro')], max_length=50)),
                ('especie_domicilio', models.CharField(choices=[('particular_permanente', 'Particular Permanente Ocupado'), ('improvisado', 'Particular Improvisado Ocupado'), ('coletivo', 'Coletivo com morador')], max_length=50)),
                ('abastecimento_agua', models.CharField(max_length=100)),
                ('agua_encanada', models.BooleanField()),
                ('agua_chega', models.CharField(max_length=100)),
                ('num_banheiros', models.PositiveIntegerField(default=0)),
                ('banheiro_compartilhado', models.BooleanField()),
                ('sanitarios', models.BooleanField()),
                ('destino_esgoto', models.CharField(max_length=100)),
                ('destino_lixo', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
                ('domicilio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contato', to='censo.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Mortalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('data_falecimento', models.DateField()),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=10)),
                ('idade_anos', models.PositiveIntegerField(blank=True, null=True)),
                ('idade_meses', models.PositiveIntegerField(blank=True, null=True)),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='falecidos', to='censo.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=10)),
                ('parentesco', models.CharField(choices=[('responsavel', 'Responsável pelo domicílio'), ('conjuge', 'Cônjuge/Companheiro(a)'), ('filho', 'Filho(a)'), ('outro', 'Outro')], max_length=50)),
                ('cor_raca', models.CharField(choices=[('branca', 'Branca'), ('preta', 'Preta'), ('amarela', 'Amarela'), ('parda', 'Parda'), ('indigena', 'Indígena')], max_length=10)),
                ('indigena', models.BooleanField(default=False)),
                ('etnia', models.CharField(blank=True, max_length=100, null=True)),
                ('fala_lingua_indigena', models.BooleanField(default=False)),
                ('quais_linguas', models.CharField(blank=True, max_length=200, null=True)),
                ('quilombola', models.BooleanField(default=False)),
                ('comunidade_quilombola', models.CharField(blank=True, max_length=100, null=True)),
                ('sabe_ler_escrever', models.BooleanField(default=None, null=True)),
                ('registro_nascimento', models.CharField(blank=True, choices=[('cartorio', 'Cartório'), ('rani', 'Registro Administrativo de Nascimento Indígena (RANI)'), ('nao_tem', 'Não tem'), ('nao_sabe', 'Não sabe')], max_length=50, null=True)),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='censo.domicilio')),
            ],
        ),
    ]
