# Generated by Django 5.2.1 on 2025-06-06 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortalidade',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='agua_chega',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='agua_encanada',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='banheiro_compartilhado',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='destino_esgoto',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='destino_lixo',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='especie_domicilio',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='num_banheiros',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='sanitarios',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='comunidade_quilombola',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cor_raca',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='etnia',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='fala_lingua_indigena',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='indigena',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='quais_linguas',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='quilombola',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='registro_nascimento',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='abastecimento_energia',
            field=models.CharField(choices=[('rede_publica', 'Rede pública'), ('gerador', 'Gerador particular'), ('energia_solar', 'Energia solar'), ('outro', 'Outro')], default='rede_publica', max_length=20, verbose_name='Como está sendo feito o abastecimento de energia elétrica?'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='chega_energia',
            field=models.BooleanField(default=False, verbose_name='Chega energia elétrica no domicílio?'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='chega_internet',
            field=models.BooleanField(default=False, verbose_name='Chega conexão de internet no domicílio?'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='demandas_principais',
            field=models.TextField(blank=True, verbose_name='Dadas as necessidades básicas, quais são as principais demandas?'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='especie',
            field=models.CharField(choices=[('particular_permanente', 'Domicílio particular permanente ocupado'), ('particular_improvisado', 'Domicílio particular improvisado ocupado'), ('coletivo', 'Domicílio coletivo com morador')], default='particular_permanente', max_length=30, verbose_name='Espécie de Domicílio'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='faleceu_alguem',
            field=models.BooleanField(default=False, verbose_name='Faleceu alguém que morava com vocês?'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='idade_falecido',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantos anos tinha ao falecer?'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='mes_ano_falecimento',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Mês e ano de falecimento (MM/AAAA)'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='nome_falecido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do falecido'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='numero_casa',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Número da Casa'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='pontos_coleta_lixo',
            field=models.TextField(blank=True, verbose_name='Quais pontos de coleta de lixo específicos da residência?'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='qtd_banheiros_com_chuveiro',
            field=models.PositiveIntegerField(default=0, verbose_name='Banheiros com chuveiro e vaso sanitário'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='qtd_banheiros_sem_chuveiro',
            field=models.PositiveIntegerField(default=0, verbose_name='Banheiros sem chuveiro (apenas vaso sanitário)'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='qtde_comodos',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de Cômodos'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='qtde_dormitorios',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de Dormitórios'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='relacao_outras_ilhas',
            field=models.TextField(blank=True, verbose_name='Como funciona a relação com as outras ilhas?'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='sexo_falecido',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], max_length=10, null=True, verbose_name='Sexo do falecido'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='situacao_ocupacao',
            field=models.CharField(choices=[('ainda_paga', 'Ainda pagando'), ('alugado', 'Alugado'), ('por_empregador', 'Por empregador'), ('por_familiar', 'Por familiar'), ('outra_forma', 'Outra forma'), ('ja_pago_herdado', 'Já pago, herdado ou ganho')], default='alugado', max_length=20, verbose_name='Este domicílio é'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='sobrenome_falecido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobrenome do falecido'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tem_internet',
            field=models.BooleanField(default=False, verbose_name='Algum morador tem acesso à internet?'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tem_maquina_lavar',
            field=models.BooleanField(default=False, verbose_name='Tem máquina de lavar roupa?'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tempo_processo_falecimento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quanto tempo demorou a conclusão do processo de falecimento?'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tipo_registro_nasc',
            field=models.CharField(choices=[('cartorio', 'Do cartório'), ('registro_administrativo_indigena', 'Registro administrativo de nascimento indígena'), ('nao_tem', 'Não tem'), ('nao_sabe', 'Não sabe')], default='nao_tem', max_length=40, verbose_name='Tem registro de nascimento?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='atividade_negocio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Qual era a principal atividade do negócio/empresa?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='autismo',
            field=models.BooleanField(default=False, verbose_name='Já foi diagnosticado(a) com autismo?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='carteira_assinada',
            field=models.BooleanField(default=False, verbose_name='Nesse trabalho tinha carteira assinada?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='concluiu_outro_superior',
            field=models.BooleanField(default=False, verbose_name='Já concluiu outro curso superior de graduação?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='curso_frequenta',
            field=models.CharField(blank=True, choices=[('1', '1 - Pré escola'), ('2', '2 - Creche'), ('3', '3 - Alfabetização jovens/adultos'), ('4', '4 - Ensino fundamental regular'), ('5', '5 - EJA fundamental'), ('6', '6 - Ensino médio regular'), ('7', '7 - Superior de graduação'), ('8', '8 - EJA médio'), ('9', '9 - Especialização (>=360h)'), ('10', '10 - Mestrado'), ('11', '11 - Doutorado'), ('12', '12 - Nenhum')], max_length=2, null=True, verbose_name='Qual curso frequenta?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='deficiencia_andar',
            field=models.CharField(blank=True, choices=[('1', 'Tem, não consegue de modo algum'), ('2', 'Tem muita dificuldade'), ('3', 'Tem alguma dificuldade'), ('4', 'Não tem dificuldade')], max_length=1, null=True, verbose_name='Dificuldade permanente para andar/subir degraus?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='deficiencia_visao',
            field=models.CharField(blank=True, choices=[('1', 'Tem, não consegue de modo algum'), ('2', 'Tem muita dificuldade'), ('3', 'Tem alguma dificuldade'), ('4', 'Não tem dificuldade')], max_length=1, null=True, verbose_name='Dificuldade permanente para enxergar (óculos/lente)?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email_respondente',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de quem respondeu'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='empresa_cnpj',
            field=models.BooleanField(default=False, verbose_name='Esse negócio/empresa era registrado no CNPJ?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado_trabalho',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado do trabalho (se for outro município)'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='faixa_rendimento',
            field=models.CharField(blank=True, choices=[('1', '1 - R$ 1,00 a 500,00'), ('2', '2 - R$ 501,00 a 1.000,00'), ('3', '3 - R$ 1.001,00 a 2.000,00'), ('4', '4 - R$ 2.001,00 a 3.000,00'), ('5', '5 - R$ 3.001,00 a 5.000,00'), ('6', '6 - R$ 5.001,00 a 10.000,00'), ('7', '7 - R$ 10.001,00 a 20.000,00'), ('8', '8 - R$ 20.001,00 a 100.000'), ('9', '9 - R$ 100.001 ou mais')], max_length=2, null=True, verbose_name='Faixa de Rendimento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='frequenta_escola',
            field=models.CharField(blank=True, choices=[('1', '1 - Sim'), ('2', '2 - Não, mas já frequentou'), ('3', '3 - Não, nunca frequentou')], max_length=1, null=True, verbose_name='Frequenta escola ou creche?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='meio_transporte',
            field=models.CharField(blank=True, choices=[('a_pe', 'A pé'), ('bicicleta', 'Bicicleta'), ('motocicleta', 'Motocicleta'), ('mototaxi', 'Mototáxi'), ('automovel', 'Automóvel'), ('taxi', 'Táxi ou assemelhados'), ('van_perua', 'Van, perua ou assemelhados'), ('onibus', 'Ônibus'), ('caminhonete_caminhao', 'Caminhonete ou caminhão adaptado'), ('embarcacao_grande', 'Embarcação de médio e grande porte'), ('embarcacao_pequena', 'Embarcação de pequeno porte'), ('outros', 'Outros')], max_length=30, null=True, verbose_name='Meio de transporte principal'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='municipio_trabalho',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Município do trabalho'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nao_se_desloca',
            field=models.BooleanField(default=False, verbose_name='Não se desloca para um local de trabalho'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do cônjuge/companheiro(a)'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome_respondente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome de quem respondeu'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qual era a ocupação, cargo ou função?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pais_trabalho',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País do trabalho'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='possui_conjuge',
            field=models.BooleanField(default=False, verbose_name='Possui cônjuge ou companheiro(a)?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='qtd_trabalhos',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3_ou_mais', '3 ou mais')], max_length=15, null=True, verbose_name='Quantos trabalhos tinha nos últimos meses?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='religiao_culto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qual é sua religião ou culto?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='retorna_trabalho_casa',
            field=models.BooleanField(default=False, verbose_name='Retorna do trabalho para casa 3 dias ou mais na semana?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone_respondente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de quem respondeu'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tempo_desloc_horas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de deslocamento casa-trabalho'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tempo_desloc_minutos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minutos de deslocamento casa-trabalho'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo_uniao',
            field=models.CharField(blank=True, choices=[('casamento_civil_religioso', 'Casamento civil e religioso'), ('somente_civil', 'Somente casamento civil'), ('somente_religioso', 'Somente casamento religioso'), ('uniao_consensual', 'União consensual')], max_length=30, null=True, verbose_name='Tipo de união'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='trabalho_em',
            field=models.CharField(blank=True, choices=[('casa_mesmo_municipio', 'Apenas em casa ou na propriedade/neste município'), ('fora_municipio', 'Fora de casa e da propriedade/neste município'), ('outro_municipio_br', 'Em outro município do Brasil'), ('outro_pais', 'Em outro país'), ('mais_de_um', 'Em mais de um município ou país')], max_length=30, null=True, verbose_name='Em que município/país trabalha?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='trabalhou_remunerado',
            field=models.BooleanField(default=False, verbose_name='Trabalhou ou estagiou em atividade remunerada em dinheiro?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='vive_com_conjuge',
            field=models.BooleanField(default=False, verbose_name='Vive em companhia de cônjuge ou companheiro(a)?'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='abastecimento_agua',
            field=models.CharField(choices=[('rede_publica', 'Rede pública (adutora/poço comunitário)'), ('poco_cacimba', 'Poço/cacimba/fonte própria'), ('cisterna', 'Cisterna'), ('outro', 'Outro')], default='rede_publica', max_length=20, verbose_name='Como está sendo feito o abastecimento de água?'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='rua',
            field=models.CharField(choices=[('R. Marina do Sol', 'R. Marina do Sol'), ('R. Marina do Frade', 'R. Marina do Frade'), ('R. Marina dos Coqueiros', 'R. Marina dos Coqueiros'), ('R. Marina da Lua', 'R. Marina da Lua'), ('R. Marina do Bosque', 'R. Marina do Bosque'), ('R. Marina Porto Bali', 'R. Marina Porto Bali'), ('R. Marina das Flores', 'R. Marina das Flores'), ('R. Marina das Estrelas', 'R. Marina das Estrelas'), ('R. Marina Ponta Leste', 'R. Marina Ponta Leste')], default='R. Marina do Sol', max_length=100, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='tipo',
            field=models.CharField(choices=[('casa', 'Casa'), ('casa_vila_condominio', 'Casa de vila ou condomínio'), ('casa_comodos_cortico', 'Habitação em casa de cômodos ou cortiço'), ('residencia_degradada', 'Estrutura residencial permanente degradada ou inacabada'), ('asilo_instituicao_idosos', 'Asilo ou outra instituição de permanência para idosos'), ('hotel_pensao', 'Hotel ou pensão'), ('alojamento', 'Alojamento'), ('outros', 'Outros')], default='casa', max_length=30, verbose_name='Tipo de Domicílio'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado (UF)'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='domicilio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moradores', to='censo.domicilio'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='parentesco',
            field=models.CharField(choices=[('responsavel', 'Pessoa responsável pelo domicílio'), ('conjuge_oposto', 'Cônjuge ou companheiro(a) de sexo diferente'), ('conjuge_mesmo', 'Cônjuge ou companheiro(a) do mesmo sexo'), ('filho_responsavel', 'Filho(a) do responsável e do cônjuge'), ('filho_apenas_responsavel', 'Filho(a) somente do responsável'), ('genro_nora', 'Genro ou Nora'), ('pais', 'Pai, Mãe, Padrasto ou Madrasta'), ('sogro', 'Sogro(a)'), ('neto', 'Neto(a)'), ('enteado', 'Enteado(a)'), ('irmao', 'Irmão ou Irmã'), ('avo', 'Avô ou Avó'), ('outro_parente', 'Outro parente'), ('agregado', 'Agregado(a)'), ('bisneto', 'Bisneto(a)'), ('pensionista', 'Pensionista'), ('empregado_domestico', 'Empregado(a) doméstico(a)'), ('parente_empregado', 'Parente do(a) empregado(a) doméstico(a)'), ('individual_coletivo', 'Individual em domicílio coletivo')], default='responsavel', max_length=30, verbose_name='Relação de Parentesco'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sabe_ler_escrever',
            field=models.BooleanField(default=False, verbose_name='Sabe ler e escrever?'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], default='M', max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sobrenome',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sobrenome'),
        ),
        migrations.DeleteModel(
            name='DadosContato',
        ),
        migrations.DeleteModel(
            name='Mortalidade',
        ),
    ]
